const products = [{
    "productId": "PKT-42061",
    "name": "Best of Vinexus 2017 Rotwein (6er-Paket)",
    "url": "https://www.vinexus.de/best-of-vinexus-2017-rotwein-6er-paket.html?_sgm_campaign=scn_61868394b28e4000&_sgm_source=PKT-42061&_sgm_action=click",
    "image": "https://www.wine-logistix.de/magento_pic/efulfillment/PKT-42061_2_.jpg",
    "imageS": "https://www.vinexus.de/media/image/1c/fc/8e/PKT-420615a507118ac631_200x200.jpg",
    "price": 49.3,
    "priceText": "€49,30",
    "oldPrice": 58.0,
    "oldPriceText": "€58,00",
    "category": ["Wein > Art > Pakete > Art > Aktionspakete", "Sale > Kategorien im Sale > Pakete", "Wein > Art > Pakete", "Wein > Art > Pakete > Art > Rotwein Pakete"],
    "categories": ["Wein", "Art", "Pakete", "Art", "Aktionspakete", "Sale", "Kategorien im Sale", "Rotwein Pakete"],
    "lastUpdateTime": 1518099000473,
    "inStock": true,
    "insertTime": 1514899645359,
    "publishTime": 1514899645359,
    "brand": "Unsere Selektion",
    "params": {
        "weight": "6 kg",
        "basePrice": "4.5 Liter (10,96 € * / 1 Liter)",
        "likeCount": "2",
        "manLogo": "https://www.vinexus.de/media/image/41/42/bd/unsere-selektion-logo.gif",
        "taxText": "inkl. MwSt. zzgl. Versandkosten",
        "stockText": "Auf Lager. Lieferzeit 1-3 Werktage",
        "isNew": "",
        "land": "",
        "region": "",
        "art": "",
        "stars": "",
        "tastes": "",
        "isAb": "",
        "rebsorte": ""
    },
    "language": "DE",
    "currency": ""
}, {
    "productId": "FT-SW-0344-NV",
    "name": "Veuve Clicquot Ponsardin Brut Magnum (1,5L)",
    "url": "https://www.vinexus.de/veuve-clicquot-ponsardin-brut-magnum-1-5l.html?_sgm_campaign=scn_61868394b28e4000&_sgm_source=FT-SW-0344-NV&_sgm_action=click",
    "image": "https://www.wine-logistix.de/magento_pic/efulfillment/FT-SW-0344_2_.jpg",
    "imageS": "https://www.vinexus.de/media/image/b6/98/4b/FT-SW-034459a187aaa03bf_200x200.jpg",
    "price": 107.0,
    "priceText": "€107,00",
    "oldPriceText": "",
    "category": ["Champagner & Sekt > Art > Champagner"],
    "categories": ["Champagner & Sekt", "Art", "Champagner"],
    "lastUpdateTime": 1518099000624,
    "inStock": true,
    "insertTime": 1511520818423,
    "publishTime": 1511520818423,
    "brand": "Veuve Clicquot",
    "params": {
        "weight": "1 kg",
        "basePrice": "1.5 Liter (71,33 € * / 1 Liter)",
        "likeCount": "",
        "manLogo": "https://www.vinexus.de/media/image/0b/b4/94/veuve-clicquot.png",
        "taxText": "inkl. MwSt. zzgl. Versandkosten",
        "stockText": "Auf Lager. Lieferzeit 1-3 Werktage",
        "isNew": "",
        "land": "Frankreich",
        "region": "Champagne",
        "art": "Champagner",
        "stars": "",
        "tastes": "brut,",
        "isAb": "",
        "rebsorte": ""
    },
    "language": "DE",
    "currency": ""
}, {
    "productId": "PKT-2821",
    "name": "Weinregion Baden - erstklassige Weingüter (6er-Paket)",
    "url": "https://www.vinexus.de/weinregion-baden-erstklassiger-weingueter-6er-paket.html?_sgm_campaign=scn_61868394b28e4000&_sgm_source=PKT-2821&_sgm_action=click",
    "image": "https://www.wine-logistix.de/magento_pic/efulfillment/PKT-2821_2_.jpg",
    "imageS": "https://www.vinexus.de/media/image/fd/a8/fb/PKT-28215a7aa11df2e92_200x200.jpg",
    "price": 66.78,
    "priceText": "€66,78",
    "oldPrice": 74.2,
    "oldPriceText": "€74,20",
    "category": ["Wein > Art > Pakete > Art > Genießer-Pakete", "Wein > Art > Pakete"],
    "categories": ["Wein", "Art", "Pakete", "Genießer-Pakete"],
    "lastUpdateTime": 1518099000702,
    "inStock": true,
    "insertTime": 1517390747188,
    "publishTime": 1517390747188,
    "brand": "Unsere Selektion",
    "params": {
        "weight": "6 kg",
        "basePrice": "4.5 Liter (14,84 € * / 1 Liter)",
        "likeCount": "",
        "manLogo": "https://www.vinexus.de/media/image/41/42/bd/unsere-selektion-logo.gif",
        "taxText": "inkl. MwSt. zzgl. Versandkosten",
        "stockText": "Auf Lager. Lieferzeit 1-3 Werktage",
        "isNew": "true",
        "land": "",
        "region": "",
        "art": "",
        "stars": "",
        "tastes": "",
        "isAb": "",
        "rebsorte": "Cuvée"
    },
    "language": "DE",
    "currency": ""
}, {
    "productId": "PKT-5109",
    "name": "5 Sterne Platter 2018 - Ausgezeichnete Weine aus Südafrika (6er-Paket)",
    "url": "https://www.vinexus.de/5-sterne-platter-2018-ausgezeichnete-weine-aus-suedafrika-6er-paket.html?_sgm_campaign=scn_61868394b28e4000&_sgm_source=PKT-5109&_sgm_action=click",
    "image": "https://www.wine-logistix.de/magento_pic/efulfillment/PKT-5109_2_.jpg",
    "imageS": "https://www.vinexus.de/media/image/ae/02/f2/PKT-51095a2641cd068a8_200x200.jpg",
    "price": 107.64,
    "priceText": "€107,64",
    "oldPrice": 119.6,
    "oldPriceText": "€119,60",
    "category": ["Wein > Art > Pakete > Art > Rotwein Pakete", "Wein > Art > Pakete", "Sale > Kategorien im Sale > Pakete"],
    "categories": ["Wein", "Art", "Pakete", "Art", "Rotwein Pakete", "Sale", "Kategorien im Sale"],
    "lastUpdateTime": 1518099000472,
    "inStock": true,
    "insertTime": 1512503620976,
    "publishTime": 1512503620976,
    "brand": "Unsere Selektion",
    "params": {
        "weight": "6 kg",
        "basePrice": "4.5 Liter (23,92 € * / 1 Liter)",
        "likeCount": "",
        "manLogo": "https://www.vinexus.de/media/image/41/42/bd/unsere-selektion-logo.gif",
        "taxText": "inkl. MwSt. zzgl. Versandkosten",
        "stockText": "Auf Lager. Lieferzeit 1-3 Werktage",
        "isNew": "",
        "land": "",
        "region": "",
        "art": "",
        "stars": "",
        "tastes": "",
        "isAb": "",
        "rebsorte": ""
    },
    "language": "DE",
    "currency": ""
}, {
    "productId": "PKT-5641",
    "name": "Pinotage aus Südafrika (6er-Paket)",
    "url": "https://www.vinexus.de/pinotage-aus-suedafrika-6er-paket.html?_sgm_campaign=scn_61868394b28e4000&_sgm_source=PKT-5641&_sgm_action=click",
    "image": "https://www.wine-logistix.de/magento_pic/efulfillment/PKT-5641_2_.jpg",
    "imageS": "https://www.vinexus.de/media/image/d5/e5/cc/PKT-56415a71662b5ed2b_200x200.jpg",
    "price": 46.2,
    "priceText": "€46,20",
    "oldPrice": 54.35,
    "oldPriceText": "€54,35",
    "category": ["Wein", "Wein > Art > Pakete", "Wein > Art > Pakete > Art > Gemischte Pakete", "Sale > Kategorien im Sale > Pakete"],
    "categories": ["Wein", "Art", "Pakete", "Gemischte Pakete", "Sale", "Kategorien im Sale"],
    "lastUpdateTime": 1518099000702,
    "inStock": true,
    "insertTime": 1517285302769,
    "publishTime": 1517285302769,
    "brand": "Unsere Selektion",
    "params": {
        "weight": "6 kg",
        "basePrice": "4.5 Liter (10,27 € * / 1 Liter)",
        "likeCount": "",
        "manLogo": "https://www.vinexus.de/media/image/41/42/bd/unsere-selektion-logo.gif",
        "taxText": "inkl. MwSt. zzgl. Versandkosten",
        "stockText": "Auf Lager. Lieferzeit 1-3 Werktage",
        "isNew": "true",
        "land": "",
        "region": "",
        "art": "",
        "stars": "",
        "tastes": "",
        "isAb": "",
        "rebsorte": "Pinotage"
    },
    "language": "DE",
    "currency": ""
}, {
    "productId": "PKT-456",
    "name": "Bouchard Finlayson - südafrikanische Eleganz in Weiß (6er-Paket)",
    "url": "https://www.vinexus.de/bouchard-finlayson-suedafrikanische-eleganz-in-weiss-6er-paket.html?_sgm_campaign=scn_61868394b28e4000&_sgm_source=PKT-456&_sgm_action=click",
    "image": "https://www.wine-logistix.de/magento_pic/efulfillment/PKT-456_2_.jpg",
    "imageS": "https://www.vinexus.de/media/image/28/ab/b7/PKT-45659f2c8ea38271_200x200.jpg",
    "price": 94.18,
    "priceText": "€94,18",
    "oldPrice": 110.8,
    "oldPriceText": "€110,80",
    "category": ["Wein > Art > Pakete > Art > Südafrika", "Wein > Art > Pakete"],
    "categories": ["Wein", "Art", "Pakete", "Art", "Südafrika"],
    "lastUpdateTime": 1518099000651,
    "inStock": true,
    "insertTime": 1511464668510,
    "publishTime": 1511464668510,
    "brand": "Bouchard Finlayson",
    "params": {
        "weight": "6 kg",
        "basePrice": "4.5 Liter (20,93 € * / 1 Liter)",
        "likeCount": "",
        "manLogo": "https://www.vinexus.de/media/image/73/29/84/bouchard-finlayson.png",
        "taxText": "inkl. MwSt. zzgl. Versandkosten",
        "stockText": "Auf Lager. Lieferzeit 1-3 Werktage",
        "isNew": "",
        "land": "Südafrika",
        "region": "",
        "art": "",
        "stars": "",
        "tastes": "",
        "isAb": "",
        "rebsorte": "Cuvée"
    },
    "language": "DE",
    "currency": ""
}];